language: java
jdk: openjdk11

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:
  - cd labOne
  - java pro_wrapper.java version
  - cd ../lab02
  - java pro_wrapper.java version

script:
  - ./pro/bin/pro version
  - ./pro/bin/pro  
