language: java
jdk: openjdk11

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

env:
  - PRO_SPECIAL_BUILD='early-access-amber'

install:
  - cd $FOLDER
  - java pro_wrapper.java version

matrix:
  include:
   - env: 
   	FOLDER=labOne
   	PRO_SPECIAL_BUILD='early-access'
   - env: 
   	FOLDER=lab02
   	PRO_SPECIAL_BUILD='early-access'
   - env: 
   	FOLDER=lab03
   	PRO_SPECIAL_BUILD='early-access-amber'
   - env: 
   	FOLDER=lab04
   	PRO_SPECIAL_BUILD='early-access-loom'

script:
  - ./pro/bin/pro version
  - ./pro/bin/pro